project:
  type: website

website:
  title: "GNSS simulator"
  
  repo-url: https://github.com/anielsen001/gnss-sim
  repo-actions: [edit, source, issue]
  
  page-footer: "Copyright 2025, Aaron Nielsen"

  back-to-top-navigation: true
  navbar:
    search: true
    left:
      - href: https://apnielsen.com
        text: My Home Page
      - href: index.qmd
        text: GNSS-SIM
    tools:
      - icon: github
        menu:
          - text: Source
            href: https://github.com/anielsen001/gnss-sim
          - text: Issue
            href: https://github.com/anielsen001/gnss-sim/issues

  # sidebar:
  #   search: true
  #   tools:
  #     - icon: github
  #       menu:
  #         - text: Source
  #           href: https://github.com/anielsen001/gnss-sim
  #         - text: Issue
  #           href: https://github.com/anielsen001/gnss-sim/issues
  #   contents:
  #     - href: index.qmd
  #       text: Home

execute:
  freeze: true
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



